ip_check:
  url: "https://api.ipify.org"
  interval: 300     # 秒（5分）

smtp:
  server: "your-mail-server"
  port: 465
  user: "your-mail-user"
  password: "your-mail-password"
  to: "receive-mail-address"
  ehlo_name: ""  # 空文字可。省略時は空文字
